version: '3.2'
services:
  mysql:
    image: mysql:5.7.26
    restart: always
    environment:
      MYSQL_DATABASE: 'routes'

      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'api'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'SEcRET'

      # Password for root access (required)
      MYSQL_ROOT_PASSWORD: 'SuPeRsEcReT'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    command:
      # UTF8 ready
      - '--character-set-server=utf8'
      - '--collation-server=utf8_general_ci'

      # Where our data will be persisted and scripts loaded
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  api:
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    expose:
      - "5000"
    command: sh -c './wait-for mysql:3306 -- ./api'
    environment:
      SOME_VAR: value
